<!-- 固定在底部 -->
<!-- 
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
-->
<!-- 静止在底部 -->
<!-- 
<nav class="navbar navbar-default navbar-static-bottom" role="navigation">
-->
<footer class="bs-footer" role="contentinfo">
    <div class="container">
        <table class="table">
        <tr>
            <th>友情链接</th>
            <th>关于</th>
            <th>帮助</th>
            <th>联系</th>
            <td rowspan="4"><img title="" alt="" src="./src/css/img/QP.png"></td>
        </tr>
        <tr>
            <td>t</td>
            <td>da</td>
            <td>ad</td>
            <td>ad</td>
        </tr>
        <tr>
            <td>adf</td>
            <td>f</td>
            <td>adf</td>
            <td>33</td>
        </tr>
        <tr>
            <td>ff</td>
            <td>ff</td>
            <td>ff</td>
            <td>aa</td>
        </tr>
        </table>
        <div class="copyright">
          Copy xxxx
        </div>
    </div>
</footer>
</BODY>
</HTML>
